version: '3.8'

services:
  api:
    image: ninepiece2/cps714-loyalty-rewards:api
    container_name: CPS714-Loyalty-Rewards-API
    ports:
      - "8443:8443"
    volumes:
      - /root/certs:/https:ro
    environment:
      - ASPNETCORE_URLS=https://*:8443;http://*:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/ssl.crt
      - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/https/ssl.key
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - Jwt:Key=${JWT_KEY}
    command: ["dotnet", "CPS714-Loyalty-Rewards-API.dll"]
    restart: always