SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FeedbackFormTopics](
	[UID] [int] IDENTITY(1,1) NOT NULL,
	[Topic] [nvarchar](250) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FeedbackFormTopics] ADD  CONSTRAINT [PK_FeedbackFormTopics] PRIMARY KEY CLUSTERED 
(
	[UID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
